/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package viewTelaUsuarioAdm;

import Construtor.construtorCliente;
import bancoDados.Conexao;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Paulo Ricardo
 */
public class frameAlterar extends javax.swing.JFrame {

    public Connection connection = null;
    public Statement statement = null;
    public ResultSet resultset = null;

    private static construtorCliente cliente;
    public static Conexao banco = new Conexao();

    private static String nomeBusca;
    private static String nome;
    private static String usuario;
    private static String senha;

    /**
     * Creates new form frameAlterar
     */
    public frameAlterar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        btnAlterar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSelecionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ALTERAR", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Book Antiqua", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel1.setText("NOME:");

        txtNomeBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtNomeBuscar.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N

        btnBuscar.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnMenu.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Icones/iconeMenu.png"))); // NOI18N
        btnMenu.setText("MENU");
        btnMenu.setActionCommand("btnMenu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "USUARIO", "SENHA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(Tabela);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel2.setText("Nome:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel3.setText("Usuário:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel4.setText("Senha:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        txtNome.setBackground(new java.awt.Color(255, 255, 255));
        txtNome.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jPanel3.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 350, -1));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jPanel3.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 350, -1));

        txtSenha.setBackground(new java.awt.Color(255, 255, 255));
        txtSenha.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jPanel3.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 350, -1));

        btnAlterar.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnAlterar.setText("ALTERAR");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        btnLimpar.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel3.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        btnSelecionar.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnSelecionar.setText("SELECIONAR");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });
        jPanel3.add(btnSelecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomeBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMenu)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMenu)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNomeBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Botão de Menu
    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed

        frameMenu menu = new frameMenu();
        menu.setVisible(true);

        frameCadastrar consultar = new frameCadastrar();
        btnMenu.addActionListener(e -> consultar.dispose());
    }//GEN-LAST:event_btnMenuActionPerformed

    //Botãp para Buscar os Dados no Banco de Dados
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        ListarClientes();
    }//GEN-LAST:event_btnBuscarActionPerformed

    //Botão para Alterar os Dados
    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        //Pegando as Informações dos TXTs e Salvando em Váriaveis
        nome = txtNome.getText();
        usuario = txtUsuario.getText();
        senha = txtSenha.getText();

        //Chamado o Construtor para salvar o dados e começar a Editar
        cliente = new construtorCliente(nome, usuario, senha);

        //Chamando a Função para Verificar se os Dados estão preenchidos
        verificarCamposSeEstaoPreechidos();


    }//GEN-LAST:event_btnAlterarActionPerformed

    //Botão para Limpar os TXTs 
    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        LimparCampos();

    }//GEN-LAST:event_btnLimparActionPerformed

    //Botão para Selecionar os Dados do Banco para Alterar
    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        try {
            //Criando uma Váriavel para Puxar as Informações da Tabela do java
            int setar = Tabela.getSelectedRow();
            //Verificando se ela for menor que 0 não vão iniciar a função do Botão
            if (setar < 0) {
                JOptionPane.showMessageDialog(null, "Selecione algum dados para ser Alterado");
            } else {
                //Selecionando os dados, aonde vamos setar o Modelo da Tabela Java , Selecionar a Posição que desejo e Colocar no TXT responsavel
                txtNome.setText(Tabela.getModel().getValueAt(setar, 1).toString());
                txtUsuario.setText(Tabela.getModel().getValueAt(setar, 2).toString());
                txtSenha.setText(Tabela.getModel().getValueAt(setar, 3).toString());

            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro : " + erro.getMessage());
        }


    }//GEN-LAST:event_btnSelecionarActionPerformed

    //Função para Listar todos os dados do Banco de dados
    public void ListarClientes() {

        //Váriavel responsável por pegar o nome da informação para filtar no banco de dados
        nomeBusca = "'%" + txtNomeBuscar.getText() + "%'";

        try {
            //Iniciando a Classe do Banco de dados
            banco.conectar();

            //Código do SQL aonde vai ser executado a função.
            var sql = "SELECT * FROM cliente WHERE Nome LIKE " + nomeBusca + " or usuario LIKE " + nomeBusca + " ";

            //Preparando o Comando SQL para ser Executado
            PreparedStatement stmt = banco.connection.prepareStatement(sql);

            //Verificando e Executando o Comando SQL
            try (var result = stmt.executeQuery()) {
                //Iniciando as propriedades da Tabela Java
                DefaultTableModel modelo = (DefaultTableModel) Tabela.getModel();
                modelo.setNumRows(0);

                if (!result.isBeforeFirst()) {
                    JOptionPane.showMessageDialog(null, "Não Existe Registro no Banco de Dados !");
                } else {
                    //Vai se repetir um loop até zerar o banco de Dados
                    while (result.next()) {
                        //Vai ser adicionado cada dado de cada linha o Banco de dados Possue. com o metodo result buscando as colunas do Banco de Dados.
                        modelo.addRow(new Object[]{result.getString("id"), result.getString("nome"), result.getString("usuario"), result.getString("senha")});

                    }

                }

            }
            //Fecha o banco de dados
            banco.connection.close();

        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro no Banco: " + erro.getMessage());
        }

    }

    public void LimparCampos() {
        txtNome.setText("");
        txtUsuario.setText("");
        txtSenha.setText("");

    }

    //Veificando os Campos se estão preenchidos
    private void verificarCamposSeEstaoPreechidos() {

        try {
            //Vefificando Se foi Preechido os Campos
            if (cliente.getNome().isEmpty() || cliente.getUsuario().isEmpty() || cliente.getSenha().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha os Campos Corretamente !!");
            } else {
                verificandoCadaCampoSeEstaPreenchido();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }

    }

    private void verificandoCadaCampoSeEstaPreenchido() {
        try {
            //Verificando se Cada Campos foi Preenchido Corretamente
            if (cliente.getNome().length() < 3) {
                JOptionPane.showMessageDialog(null, "Campo Nome Precisa ter no Minino 3 Caracteres");
            } else if (cliente.getUsuario().length() < 5) {
                JOptionPane.showMessageDialog(null, "Campo Usuário Precisa ter no Minino 5 Caracteres");

            } else if (cliente.getSenha().length() < 6) {
                JOptionPane.showMessageDialog(null, "Campo Senha Precisa ter no Minino 6 Caracteres");
            } else {
                cadastrarClienteNoBanco();

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }

    }

    //Alterando os Dados do Banco
    private void cadastrarClienteNoBanco() {

        try {
            //Conectando ao Banco de Dados
            banco.conectar();

            //Verificando se Foi Estabelecida conexão com o Banco
            if (banco.estaConectado()) {

                //Iniando as informações da Tabela Java
                int setar = Tabela.getSelectedRow();

                //Alterando o Clienete no Banco de Dados
                //Foi colocado como o ID a primeira Posição do Cliente Selecionado lá na Tabela Java.
                banco.EditarCliente(Tabela.getModel().getValueAt(setar, 0).toString(), cliente.getNome(), cliente.getUsuario(), cliente.getSenha());
                JOptionPane.showMessageDialog(null, "Clienete Alterado Com Sucesso !!");
                LimparCampos();

                banco.DesconectarBanco();

            } else {
                JOptionPane.showMessageDialog(null, "Banco Não Está Conectado !!");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            banco.DesconectarBanco();
        } finally {
            banco.DesconectarBanco();
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frameAlterar().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeBuscar;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
